###
GET http://localhost:3000/api/get-product/9dpigJk6YE7dL4E54u03

###
DELETE http://localhost:3000/api/delete-product/VVAm4mvfMRg0fdr1Vcmy

###
POST http://localhost:3000/api/create-product
Content-Type: application/json

{
  "name": "xpto",
  "quantity": 1
}
